### ISSUE TITLE
Ruby installed gems non-root user?

### ISSUE THREAD

**Issue by iniweb** [geerlingguy/ansible-role-ruby#11]
I used Vagrant and Ansible as provision. There is options to install gems or give access for non-root users?

I set:
```
ruby_install_gems: ['compass:0.12.6', 'sass:3.4.9']
```
All works fine, but gems installed in /root/.gem/ruby/2.1.0/bin and vagrant user doesn't has access for binary files like compass.

Solution for me, instead of using ruby_install_gems i wrote task:
```
  - name: Install Ruby gems
    sudo: no
    gem: name={{ item.name }} version={{ item.version }} state=present
    with_items: ruby_gems
```

**Comment by geerlingguy** [comment]
+1

**Comment by fubarhouse** [comment]
Something I addressed in my own role a while back.

See the following link for a working example:
https://github.com/fubarhouse/fubarhouse.ruby/blob/c8ec0775773b3c13bd059c73c14980c612beb4de/tasks/gems.yml

**Comment by opdavies-cti** [comment]
I noticed this also.

**Comment by opdavies** [comment]
I noticed this also.

**Comment by geerlingguy** [comment]
Hopefully this works now... if some people could test it and make sure it's working for various use cases, that'd be great :)

**Comment by fubarhouse** [comment]
Looks good to me, I'll test it later :)
