### ISSUE TITLE
Updating ruby version does not work.

### ISSUE THREAD

**Issue by ocha** [geerlingguy/ansible-role-ruby#35]
I used role to install ruby from source on a given machine. Later, I changed ruby version/url to a newer release and re-ran the role against the machine. I was expecting new version of ruby to be installed on the system. However role skips installation of ruby from source if there is any ruby already present on the system. 

Is this an expected and correct behaviour for the role? If not, I can try to fix it and submit a PR for it.

Thanks,
Iuri

**Comment by j15e** [comment]
You may remove the `creates=/usr/local/bin/ruby` line here : 

https://github.com/geerlingguy/ansible-role-ruby/blob/76e80c22eb04902daf2e187891bf863e0e7de578/tasks/install-from-source.yml#L40-L48

But not that this will ALWAYS compile & install ruby, so this is not perfect either. 

We would need a way to know that the specific version of ruby was already compiled & installed, but the output file is always the same (`/usr/local/bin/ruby`). Would need to check the checksum of the files but I don't know how to do this simply with the Ansible language.

**Comment by ocha** [comment]
Changing it to support updating of installed ruby version when installing from source is easy. I was wondering if it is in the scope for this role or not installing from source when any version of ruby is present is desired behavior.

**Comment by cpence** [comment]
You don't have to check the checksum; you can parse the output of `ruby -v` to see if it matches what the user has set as the Ruby version. This would be *really* helpful for me, as I often need to update the version of Ruby on provisioned servers... Will see if I have time to assemble a PR for this.
