### ISSUE TITLE
Variables starting with underscore violate Ansible documentation rule

### ISSUE THREAD

**Issue by jlmuir** [geerlingguy/ansible-role-ruby#64]
In `vars/{Debian,RedHat}.yml`, two variables are defined that start with an underscore character: `__ruby_packages` and `__ruby_build_packages`, but in the Ansible User Guide at Working With Playbooks > Using Variables > [Creating valid variable names](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#creating-valid-variable-names), it says:

> Variable names should be letters, numbers, and underscores. Variables should always start with a letter.

**Comment by jlmuir** [comment]
Hmm, now I see that you do this in a number of your published roles and recommend it in your "Ansible for DevOps" book in Appendix B - Ansible Best Practices and Conventions > Playbook Organization > Use role defaults and vars correctly.

Frankly, this scheme seems quite reasonable to me, and I'd like to use it in roles I create, but I'm struggling with how to reconcile it with the variable naming rule I pointed out in the Ansible User Guide.

**Comment by vvitad** [comment]
Thats is actually quite interesting after 4 years.
