### ISSUE TITLE
install_from_source does not upgrade ruby

### ISSUE THREAD

**Issue by getjack** [geerlingguy/ansible-role-ruby#68]
In the task install_from_source.yml the following step should install ruby on your host:

```
- name: Build ruby.
  command: >
    {{ item }}
    chdir={{ workspace }}/ruby-{{ ruby_version }}
    creates=/usr/local/bin/ruby
  with_items:
    - "{{ ruby_source_configure_command }}"
    - make
    - make install
```

However, if you installed Ruby once e.g. in version 2.4 and now want to upgrade to version 2.5 the task will be marked as ok because the path /usr/local/bin/ruby was created with version 2.4.

Extract from the https://docs.ansible.com/ansible/latest/modules/command_module.html docs

`creates:  A filename or (since 2.0) glob pattern. If it already exists, this step won't be run.`

**Comment by jdelStrother** [comment]
Would love to hear a good workaround for this, I always end up temporarily deleting the `creates` line 😬

**Comment by seuros** [comment]
I changed the script to touch a file with the version as suffix.
```yaml
- name: Build ruby.
  command: >
    {{ item }}
    chdir={{ workspace }}/ruby-{{ ruby_version }}
    creates=/usr/local/bin/.ruby-{{ ruby_version }}
    warn=false
  with_items:
    - "{{ ruby_source_configure_command }}"
    - make
    - make install
    - touch /usr/local/bin/.ruby-{{ ruby_version }}
